
import Consultas.Consultas;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.FontFactory;
import consultoria.DatosProfesor;
import consultoria.LeerDatos;
import generarPDF.DTOFormato;
import generarPDF.PDF;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Cristopher Inces
 */
public class DestallesProfesor extends javax.swing.JFrame {

    ArrayList<String> cursos = new ArrayList<>();
    ArrayList<String> especializacion = new ArrayList<>();
    int Sheet=0;

    /**
     * Creates new form DestallesProfesor
     */
    public DestallesProfesor(int Sheet) {
        initComponents();
        this.Sheet=Sheet;
        //LlenarTablas();
        try {
            DatosProfesor.datosConsulturiaProfesor = LeerDatos.procesarBaseDatosExcel(Sheet);
        } catch (IOException ex) {
            Logger.getLogger(DestallesProfesor.class.getName()).log(Level.SEVERE, null, ex);
        }
        especializacion = DatosProfesor.obtenerAreaEspecialidadOTrabajoProfesor();
        cursos = DatosProfesor.obtenerCursosQueImpartiriaProfesor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCursos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaAreas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cursos interesados en impartir");

        jLabel2.setText("Areas de Especialización");

        TablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaCursos);

        TablaAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaAreas);

        jButton1.setText("Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DTOFormato dto = new DTOFormato();
        dto.setFondoEncabezado(new BaseColor(204, 255, 102));
        dto.setFondoIntermedio(new BaseColor(216, 214, 214));
        dto.setFormatoTexto(FontFactory.getFont(FontFactory.HELVETICA, 13, BaseColor.BLACK));

        PDF pdf = new PDF(dto);
        pdf.añadirTitulo(DatosProfesor.obtenerNombreProfesor());
        pdf.añadirSubtitulo("Cursos que impartiria profesor");
        String[] Encabezado1 = {"Curso"};
        String[][] List1 = new String[cursos.size()][1];
        for (int i = 0 ; i < cursos.size() ; i++){
            String[] temp = {cursos.get(i)};
            List1[i]=temp;
        }
        pdf.añadirTabla(Encabezado1, List1);
        pdf.añadirSalto();
        
        pdf.añadirSubtitulo("Areas de especialización del profesor");
        String[] Encabezado2 = {"Areas de Especializacion"};
        String[][] List2 = new String[especializacion.size()][1];
        for (int i = 0 ; i < especializacion.size() ; i++){
            String[] temp = {especializacion.get(i)};
            List2[i]=temp;
        }
        pdf.añadirTabla(Encabezado2, List2);
        
        pdf.generarDocumento();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void CargarDatosProfesor() {
        this.setTitle(DatosProfesor.obtenerNombreProfesor());
        
        DefaultTableModel modelocursos = new DefaultTableModel();
        modelocursos.addColumn("Cursos");
        for (int i = 0; i < cursos.size(); i++) {
            String[] temp = new String[1];
            temp[0] = cursos.get(i);
            modelocursos.addRow(temp);
        }
        TablaCursos.setModel(modelocursos);

        DefaultTableModel modeloareas = new DefaultTableModel();
        modeloareas.addColumn("Areas");
        for (int i = 0; i < especializacion.size(); i++) {
            String[] temp = new String[1];
            temp[0] = especializacion.get(i);
            modeloareas.addRow(temp);
        }
        TablaAreas.setModel(modeloareas);

    }

    private void LlenarTablas() {

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaAreas;
    private javax.swing.JTable TablaCursos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
