
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import Consultas.Consultas;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kenneth
 */
public class InformacionProfesor extends javax.swing.JFrame {

    /**
     * Creates new form InformacionProfesor
     *
     */
    int posProfesor;
    public InformacionProfesor(int profesorRow) throws IOException, NoSuchMethodException, InvocationTargetException, IllegalAccessException {
        posProfesor = profesorRow;
        initComponents();
        this.prepararTablaInformativa();
    }
    public InformacionProfesor(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaInformativaProfesor = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informacion del profesor");

        TablaInformativaProfesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Profesor", "Información"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaInformativaProfesor.setAlignmentX(15.0F);
        TablaInformativaProfesor.setAlignmentY(10.0F);
        TablaInformativaProfesor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TablaInformativaProfesor.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablaInformativaProfesor.setRequestFocusEnabled(false);
        TablaInformativaProfesor.setRowHeight(70);
        jScrollPane1.setViewportView(TablaInformativaProfesor);
        if (TablaInformativaProfesor.getColumnModel().getColumnCount() > 0) {
            TablaInformativaProfesor.getColumnModel().getColumn(0).setPreferredWidth(200);
            TablaInformativaProfesor.getColumnModel().getColumn(1).setResizable(false);
            TablaInformativaProfesor.getColumnModel().getColumn(1).setPreferredWidth(1350);
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(743, 743, 743)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        try {
            new VentanaNombreProfesores().setVisible(true);
        } catch (IOException | NoSuchMethodException | InvocationTargetException | IllegalAccessException ex) {
            Logger.getLogger(PlanCapacitacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionProfesor().setVisible(true);
            }
        });
    }
    
        private ArrayList<ArrayList<Object>> llamarMetodos() throws IOException, NoSuchMethodException, InvocationTargetException, IllegalAccessException{
            ArrayList<ArrayList<Object>> listaExtrema = new ArrayList<ArrayList<Object>>();
            Consultas consult = new Consultas();
            listaExtrema.add(consult.getDataByMethod("obtenerNombreProfesor"));
            listaExtrema.add(consult.getDataByMethod("obtenerTipoIdentificacionProfesor"));
            listaExtrema.add(consult.getDataByMethod("obtenerCedulaProfesor"));
            listaExtrema.add(consult.getDataByMethod("obtenerNumeroPasaporteProfesor"));
            listaExtrema.add(consult.getDataByMethod("obtenerPaisProcedenciaProfesor"));
            listaExtrema.add(consult.getDataByMethod("obtenerPuestosActualmenteProfesor"));
            listaExtrema.add(consult.getDataByMethod("obtenerAreaEspecialidadOTrabajoProfesor"));
            listaExtrema.add(consult.getDataByMethod("obtenerCursosQueImpartiriaProfesor"));
            listaExtrema.add(consult.getDataByMethod("obtenerRegimenPensionProfesor"));
            listaExtrema.add(consult.getDataByMethod("conoceCuotasCanceladas"));
            listaExtrema.add(consult.getDataByMethod("obtenerCuotasCanceladasProfesor"));
            listaExtrema.add(consult.getDataByMethod("obtenerEdadPensionarseProfesor"));
            listaExtrema.add(consult.getDataByMethod("obtenerTituloYGradoAcedemicoProfesor"));
            listaExtrema.add(consult.getDataByMethod("obtenerEstudiosPegradoYUbicacionDondeLosObtuvoProfesor"));
            
            return listaExtrema;
    }
        
    private void prepararTablaInformativa() throws IOException, NoSuchMethodException, InvocationTargetException, IllegalAccessException{
        
        ArrayList<ArrayList<Object>> listaExtrema = this.llamarMetodos();
        Consultas consult = new Consultas();
        DefaultTableModel modelo = (DefaultTableModel) TablaInformativaProfesor.getModel();
        ArrayList<String> columnas = new ArrayList<String>();
        columnas.add("Nombre");
        columnas.add("Tipo de identificación");
        columnas.add("Cédula");
        columnas.add("Pasaporte");
        columnas.add("País de origen");
        columnas.add("Puestos actuales");
        columnas.add("Especialidades");
        columnas.add("Posibles cursos");
        columnas.add("Régimen de pensión");
        columnas.add("Conoce sus cuotas canceladas");
        columnas.add("Cuotas canceladas");
        columnas.add("Edad de pensión");
        columnas.add("Grado académico");
        columnas.add("Pre-grado");
        
        for (int i = 0; i < 13; i++) {
            System.out.println(listaExtrema.get(0));
            Vector row = new Vector();
            row.add(columnas.get(i));
            try{
                           row.add("<html>" + listaExtrema.get(i).get(this.posProfesor).toString().replace("[","").replace("]","") +"</html>"); 
            }
            catch(Exception e){
                            row.add(listaExtrema.get(i).get(this.posProfesor).toString());
            }

            modelo.addRow(row);
        }
        //NewCellStyle gg = new NewCellStyle();
        //TablaInformativaProfesor.getcol("Información").setCellRenderer(gg);
        TablaInformativaProfesor.setModel(modelo);
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaInformativaProfesor;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
